### PR TITLE
Feat: New sizes for Button, IconButton & Icon

### LINKED ISSUE #139: Feature: support 3 sizes in buttons & icons
## Description

Currently, `Button` and `IconButton` have 2 sizes: `small` and `large`. 

In the meantime, `Icon` has 3 sizes: `x-small`, `small` and `large`

We want to make sure that all the above components have exactly 3 sizes: `small`, `medium` and `large` and their sizes abide to the designs

## Designs

https://app.abstract.com/projects/ab14d6c7-511b-4577-8de9-25ca9cd2918b/branches/master/commits/b158e16e90b6a2d871a089640b51cc8a4c65c8ef/files/80211ea4-8009-417c-883f-6c096a2959bb/layers/008E0080-642C-4F61-9632-19A8CFD0E76D

## Acceptance Criteria

- `Button` has 3 `size`  variants: `small`, `medium` and `large`
- `IconButton has 3 `size` variants: `small`, `medium` and `large`
- `Icon` has 3 `size` variants: `small`, `medium` and `large`
- Snapshot tests are added for all elements
- Elements visually abide to the designs (size-wise)

### PR DESCRIPTION
**Pull request by 3nvi**
### Background

Our designs call for the use of additional sizes for the `Button` and `IconButton` components, which naturally means that `Icon` has the support additional sizes as well.

Up until now we had  `small` and `large`. With this PR, we add a `medium` size, allowing us to have some stuff ready for future design needs

Closes #139 

### Changes

- Add `medium` size on `Button` and refactor implementation to use `height` instead of `padding`
- Add `medium` size on `Icon` and refactor implementation to use `width` & `height` instead of `padding`
- Add `medium` size on `Icon`
- Add dynamic icon size on both `Button` and `IconButton`
- Update needed docs with new sizes
- Refactor other components due to `size` changes
- Add snapshot tests for all sizes
- Add 2 new icons (as a side-effect)

### Refactors

- `<Icon>`: Whatever is `small` became `medium` 
- `<IconButton>`: Whatever is `small` became `medium`
- `<Button>`: Whatever was `small` became`medium`

### Related Acceptance Criteria

https://github.com/panther-labs/pounce/issues/139

### Designs

https://app.abstract.com/projects/ab14d6c7-511b-4577-8de9-25ca9cd2918b/branches/master/commits/1bcf5805564e7411d307e0b3c243eab6726d18d6/files/80211ea4-8009-417c-883f-6c096a2959bb/layers/008E0080-642C-4F61-9632-19A8CFD0E76D?mode=build&selected=root-008E0080-642C-4F61-9632-19A8CFD0E76D

### Screenshots

Screen Shot 2020-10-02 at 3 09 56 PM
Screen Shot 2020-10-02 at 3 10 15 PM

### Testing

- Snapshot tests for all `size` on `Button`
- Snapshot tests for all `size` on `IconButton`

### CODE REVIEW

**Review by vorillaz — APPROVED** [review]
LGTM, one minor comment. Since the "medium" size is used heavily, should we somehow place it as a default without overriding any piece of code available?

**Comment by 3nvi** [comment]
> LGTM, one minor comment. Since the "medium" size is used heavily, should we somehow place it as a default without overriding any piece of code available?

@vorillaz I was thinking the same, but that's for `IconButton` and `Icon` only.

Currently the most used `Button` is `large`, so I feel that `IconButton` should "mimic" that. That's why both `Button` and `IconButton` are aligned.

Now `Icon` can have a different default, I just feel it would be more complex to update Panther & Panther Enterprise afterwards. Right now the refactoring methodology is "everything that was `small` has to be `medium`".

Overall, I think if we changed the default `size`, it should only be done for `Icon`. Do you think we should do it?

**Comment by vorillaz** [comment]
@3nvi Cool, I agree I just tried spotting the culprit without actually needed so. 
Ship it.

**Pull request merged**
